import pg from 'pg';

const connectionString = 'postgres://postgres:Olawale123@db.tzfltfqqlijbtuqioidi.supabase.co:5432/postgres';

const client = new pg.Client({
  connectionString,
});

async function run() {
  try {
    console.log('Connecting to Supabase PostgreSQL database...');
    await client.connect();
    console.log('Connected successfully!');

    const sql = `
      -- Store scraper results for caching (avoid hitting APIs repeatedly)
      CREATE TABLE IF NOT EXISTS scraper_cache (
        id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
        scraper_type TEXT NOT NULL, -- hashtags | emails | articles | news
        query TEXT NOT NULL,         -- the keyword or domain searched
        result JSONB NOT NULL,       -- full API response stored
        created_at TIMESTAMPTZ DEFAULT NOW(),
        expires_at TIMESTAMPTZ DEFAULT (NOW() + INTERVAL '24 hours')
      );

      -- Media assets (music, images, videos generated by agents)
      CREATE TABLE IF NOT EXISTS media_assets (
        id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
        client_id UUID REFERENCES clients(id),
        task_id UUID REFERENCES agent_tasks(id),
        asset_type TEXT NOT NULL, -- music | image | video | document
        url TEXT NOT NULL,
        metadata JSONB,           -- duration, dimensions, prompt used, etc.
        status TEXT DEFAULT 'ready', -- ready | used | archived
        created_at TIMESTAMPTZ DEFAULT NOW()
      );

      CREATE INDEX IF NOT EXISTS idx_scraper_cache_query ON scraper_cache(scraper_type, query);
      CREATE INDEX IF NOT EXISTS idx_scraper_cache_expires ON scraper_cache(expires_at);
      CREATE INDEX IF NOT EXISTS idx_media_assets_client ON media_assets(client_id);
    `;

    console.log('Running tables creation SQL...');
    await client.query(sql);
    console.log('✅ Tables and indices successfully created in Supabase!');
  } catch (err) {
    console.error('❌ Error executing SQL:', err.message);
  } finally {
    await client.end();
  }
}

run();
